name: bettas_alarm
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.2.0
  flutter_local_notifications: ^21.0.0
  alarm: ^5.4.0
  timezone: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/indian_alarm.mp3
  fonts:
    - family: Minecraft
      fonts:
        - asset: assets/Minecraft.ttf
          weight: 400